# Generated by Django 2.2 on 2022-01-15 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adid', models.IntegerField(blank=True)),
                ('address', models.CharField(max_length=120)),
                ('metro', models.CharField(max_length=120)),
                ('square', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='imgcian/</<django.db.models.fields.IntegerField>')),
                ('description', models.TextField()),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='home.AdsCategory')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ad management',
                'verbose_name_plural': 'Ad management',
                'db_table': 'tb_ad',
                'ordering': ('-created',),
                'unique_together': {('address', 'title', 'category', 'photo')},
            },
        ),
    ]
