# Generated by Django 2.2 on 2022-01-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='adid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.ImageField(blank=True, upload_to='imgcian/'),
        ),
    ]
