# Generated by Django 2.2 on 2022-01-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPESModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.FloatField()),
                ('m1', models.FloatField()),
                ('m2', models.FloatField()),
                ('m3', models.FloatField()),
                ('m4', models.FloatField()),
                ('m5', models.FloatField()),
                ('m6', models.FloatField()),
                ('m7', models.FloatField()),
                ('m8', models.FloatField()),
                ('m9', models.FloatField()),
                ('m10', models.FloatField()),
                ('m11', models.FloatField()),
                ('m12', models.FloatField()),
                ('m13', models.FloatField()),
                ('m14', models.FloatField()),
                ('m15', models.FloatField()),
                ('s1', models.FloatField()),
                ('c1', models.FloatField()),
            ],
            options={
                'verbose_name': 'Model management',
                'verbose_name_plural': 'Model management',
                'db_table': 'tb_tempModel',
            },
        ),
    ]
